"""remove unique constraint for username

Revision ID: 06546a148433
Revises: e9c5b5c525b2
Create Date: 2023-12-03 13:19:15.851870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06546a148433'
down_revision = 'e9c5b5c525b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
